name: Run Python Script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Tesseract
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr

    - name: Run script
      run: |
        python main.py
      env:
        TESSERACT_CMD: /usr/bin/tesseract
